# istio policy
apiVersion: "rbac.istio.io/v1alpha1"
kind: ClusterRbacConfig
metadata:
  name: default
spec:
  mode: 'ON_WITH_INCLUSION'
  inclusion:
    namespaces: ["default"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: www
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: db
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: auth
---
apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRole
metadata:
  name: db-role
  namespace: default
spec:
  rules:
  - services: ["db.default.svc.cluster.local"]
    methods: ["GET", "POST"]
    paths: ["*"]
---
apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRole
metadata:
  name: auth-role
  namespace: default
spec:
  rules:
  - services: ["auth.default.svc.cluster.local"]
    methods: ["GET", "POST"]
    paths: ["*"]
---
apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRoleBinding
metadata:
  name: www-to-db
  namespace: default
spec:
  subjects:
  - user: "cluster.local/ns/default/sa/www"
  roleRef:
    kind: ServiceRole
    name: "db-role"
---
apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRoleBinding
metadata:
  name: www-to-auth
  namespace: default
spec:
  subjects:
  - user: "cluster.local/ns/default/sa/www"
  roleRef:
    kind: ServiceRole
    name: "auth-role"