apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: www
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: www
    spec:
      containers:
        - name: microsimclient
          image: kellybrazil/microsimclient
          ports:
            - containerPort: 5000
          env:
            - name: REQUEST_URLS
              value: "http://auth.default.svc.cluster.local:8080,http://db.default.svc.cluster.local:8080"
            - name: REQUEST_INTERNET
              value: "True"
            - name: SEND_SQLI
              value: "True"
            - name: SEND_XSS
              value: "True"
            - name: SEND_DGA
              value: "True"
            - name: SEND_DIR_TRAVERSAL
              value: "True"
            - name: REQUEST_MALWARE
              value: "True"
            - name: REQUEST_WAIT_SECONDS
              value: "0.5"
            - name: REQUEST_BYTES
              value: "4096"
            - name: STATS_PORT
              value: "5000"
            - name: STATSD_HOST
              value: "statsd-stats.default.svc.cluster.local"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: auth
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: microsimserver
          image: kellybrazil/microsimserver
          ports:
            - containerPort: 8080
            - containerPort: 5000
          env:
            - name: RESPOND_BYTES
              value: "32768"
            - name: STATS_PORT
              value: "5000"
            - name: STATSD_HOST
              value: "statsd-stats.default.svc.cluster.local"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: db
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: microsimserver
          image: kellybrazil/microsimserver
          ports:
            - containerPort: 8080
            - containerPort: 5000
          env:
            - name: RESPOND_BYTES
              value: "32768"
            - name: STOP_SECONDS
              value: "420"
            - name: STOP_PADDING
              value: "True"
            - name: STATS_PORT
              value: "5000"
            - name: STATSD_HOST
              value: "statsd-stats.default.svc.cluster.local"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: statsd
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: statsd
    spec:
      containers:
        - name: statsd
          image: graphiteapp/graphite-statsd
          ports:
            - containerPort: 80
              name: www
            - containerPort: 8125
              protocol: UDP
              name: stats
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: www
  name: www
spec:
  externalTrafficPolicy: Local
  ports:
    - port: 80
      targetPort: 5000
  selector:
    app: www
  sessionAffinity: None
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: statsd-www
  name: statsd-www
spec:
  externalTrafficPolicy: Local
  ports:
    - port: 80
      targetPort: 80
      name: statsd-www
  selector:
    app: statsd
  sessionAffinity: None
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: statsd-stats
  name: statsd-stats
spec:
  ports:
    - port: 8125
      targetPort: 8125
      name: stats
      protocol: UDP
  selector:
    app: statsd
  sessionAffinity: None
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: auth
  name: auth
spec:
  ports:
    - port: 8080
      targetPort: 8080
      name: auth
    - port: 5000
      targetPort: 5000
      name: stats
  selector:
    app: auth
  sessionAffinity: None
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: db
  name: db
spec:
  ports:
    - port: 8080
      targetPort: 8080
      name: db
    - port: 5000
      targetPort: 5000
      name: stats
  selector:
    app: db
  sessionAffinity: None
